# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false #ignore warnings in osx

matrix:
  include:
    - os: linux
      r: 
        - release
        - devel
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode12.2
      r: 
        - release
        - devel
#addons:
#  homebrew:
#    packages:
#    - libgit2
